<?php
function update_proxy_conf() {
    $localfile = "/etc/nginx/autogen-conf/freeshell.conf";
    $fp = fopen($localfile, "w");
    fwrite($fp, nginx_conf_gen_for_proxy());
    fclose($fp);
    chmod($localfile, 0644);
    local_update_proxy_conf();
    ssh_update_proxy_conf($localfile);
}

function nginx_conf_gen_for_proxy() {
    $conf = '## This file is automatically generated by freeshell. DO NOT MODIFY!';
    $rs = mysql_query("SELECT http_subdomain, nodeno, id FROM shellinfo");
    while ($row = mysql_fetch_array($rs)) {
        $domain = $row['http_subdomain'];
        if (empty($domain) || 0 != subdomain_check_norepeat($domain))
            continue;
        $nodeno = $row['nodeno'];
        $httpport = appid2httpport($row['id']);
        $conf .= conf_for_one_subdomain($domain, $nodeno, $httpport);
    }
    return $conf;
}

function conf_for_one_subdomain($domain, $nodeno, $httpport) {
    return "
server {
        listen 80;
        listen 443;
        listen [::]:80;
        listen [::]:443;
        server_name $domain.freeshell.ustc.edu.cn;
        access_log /var/log/nginx/freeshell-proxy/access.log logverbose;
        error_log  /var/log/nginx/freeshell-proxy/error.log;
        location / {
                proxy_pass       http://s$nodeno.freeshell.ustc.edu.cn:$httpport;
                proxy_set_header X-Real-IP  \$remote_addr;
                proxy_set_header Host       \$http_host;
                proxy_set_header X-Scheme   \$scheme;
        }
}
";
}

function runas_monitor($cmd) {
    return exec("sudo -u scgyshell-monitor $cmd");
}

function local_update_proxy_conf() {
    exec("sudo /usr/local/bin/reload-nginx");
}

function ssh_update_proxy_conf($tmpfile) {
    $host = '202.38.70.159';
    $userhost = "scgyshell-client@$host";
    runas_monitor("/usr/bin/scp $tmpfile $userhost:~/freeshell-proxy");
    runas_monitor("/usr/bin/ssh $userhost chmod 644 freeshell-proxy");
    runas_monitor("/usr/bin/ssh $userhost sudo /etc/init.d/nginx reload");
}

function subdomain_check_norepeat($domain) {
    if (strlen($domain) < 3 || strlen($domain) > 20)
        return 1;
    if (!preg_match('/^[a-z0-9][a-z0-9-]+[a-z0-9]$/', $domain))
        return 2;
    if (in_array($domain, array('master', 'proxy', 'lug', 'freeshell', 'test', 'example')))
        return 3;
    return 0;
}

function subdomain_check($domain) {
    $flag = subdomain_check_norepeat($domain);
    if ($flag)
        return $flag;
    $rs = mysql_fetch_array(mysql_query("SELECT * FROM shellinfo WHERE `http_subdomain`='$domain'"));
    if ($rs)
        return 4;
    return 0;
}
