#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    exit 1
fi

local_ips="202.141.160.99 202.141.176.99"
local_port=$1
remote_ip=$2
remote_port=$3

function iptables_replace(){
    iptables -t nat -D $@
    iptables -t nat -A $@
}

for local_ip in $local_ips; do
    iptables_replace PREROUTING -d $local_ip/32 -p tcp -m tcp --dport $local_port -j DNAT --to-destination $remote_ip:$remote_port
done
iptables_replace POSTROUTING -d $remote_ip/32 -p tcp -m tcp --dport $remote_port -j MASQUERADE
