#!/bin/bash

[ -z "$1" ] && exit 1
username=$1
domain=$1

KEYDIR=/etc/nginx/freeshell-keys
TMP_KEYDIR=/tmp/freeshell-uploaded-keys/$1
[ -d "$TMP_KEYDIR" ] || exit 100
cd $TMP_KEYDIR || exit 100

modkey=$(openssl rsa -noout -modulus -in ssl.key) || exit 101
modcrt=$(openssl x509 -noout -modulus -in ssl.crt) || exit 102
[ "$modkey" = "$modcrt" ] || exit 103

openssl verify -CApath /etc/ssl/certs/ -purpose sslserver -untrusted intermediate.crt ssl.crt || exit 104

wildcard_domain="*.${domain#*.}"
grepvar=$(echo "DNS:\\($domain\|$wildcard_domain\\)" | sed 's/\./\\./g' | sed 's/\*/\\*/g')
(openssl x509 -certopt no_subject,no_header,no_version,no_serial,no_signame,no_validity,no_subject,no_issuer,no_pubkey,no_sigdump,no_aux -text -noout -in ssl.crt | grep "$grepvar") || exit 106

cat ssl.crt >$KEYDIR/$username.crt || exit 107
echo "" >>$KEYDIR/$username.crt || exit 107  # in case no CRLF after first crt
cat intermediate.crt >>$KEYDIR/$username.crt || exit 107

cat ssl.key >$KEYDIR/$username.key || exit 108
rm -f $TMP_KEYDIR/*

exit 0
