#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    exit 1
fi

local_ips="202.141.160.99 202.141.176.99"
action=$1
local_port=$2
remote_ip=$3
remote_port=$4

function iptables_delete(){
    iptables -t nat -D $@
}
function iptables_replace(){
    iptables -t nat -D $@
    iptables -t nat -A $@
}

if [ "$action" == "add" ]; then
    for local_ip in $local_ips; do
        iptables_replace PREROUTING -d $local_ip/32 -p tcp -m tcp --dport $local_port -j DNAT --to-destination $remote_ip:$remote_port
    done
    iptables_replace POSTROUTING -d $remote_ip/32 -p tcp -m tcp --dport $remote_port -j MASQUERADE
    exit 0
fi

if [ "$action" == "remove" ]; then
    for local_ip in $local_ips; do
        iptables_delete PREROUTING -d $local_ip/32 -p tcp -m tcp --dport $local_port -j DNAT --to-destination $remote_ip:$remote_port
    done
    iptables_delete POSTROUTING -d $remote_ip/32 -p tcp -m tcp --dport $remote_port -j MASQUERADE
    exit 0
fi

exit 1
